### ISSUE TITLE
useless wrapper script?

### ISSUE THREAD

**Issue by 0xaf1f** [fanglab/SMALR#12]
You have `smalr` and `call_smalr.py`, and the only thing that `smalr` does is call the latter. I'd suggest renaming `call_smalr.py` to `smalr` and getting rid of the shell script.

Also, please keep the tags up-to-date. I see the version string in the code is 1.0.1, ahead of the latest tag.

Thanks for all your work.

**Comment by jbeaulaurier** [comment]
Hi,

Yep, thanks for the great suggestions. I've done you one better and eliminated both the shell script (smalr) and the call_smalr.py file. Instead, I've added "smalr" as an entry_point in setup.py, which launches the pipeline. So command line usage isn't affected, but the behind the scenes action is much cleaner. See e80b153800411dc0aa45230a82f1f53257772a83 for the details.

I've also just added a new v1.1 release.

-John
