### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by 0xaf1f** [fanglab/SMALR#4]
I noticed you have labeled a version in `__init__.py`, but it would be helpful if you could tag the associated snapshot as such.  Github will make tagged versions available for download in the Releases tab. If you choose acceptable license terms (#3), we would rely on the release tags as the versions to package. New tags would indicate to us by our version scanner that a new version is available and we can then update the package.

**Comment by jbeaulaurier** [comment]
Hi Afif-
These are both great suggestions and I will address them ASAP. 
Thanks,
John

**Comment by andersgs** [comment]
Please tag a release. Thank you. A.

**Comment by jbeaulaurier** [comment]
Thanks for the reminder on this. Release v1.0 has just been [added](https://github.com/fanglab/SMALR/releases/tag/v1.0).

-John
