### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'gnorin'

### ISSUE THREAD

**Issue by juandu** [fanglab/SMALR#5]
Hi John, I was running the test files you have provided and ran into this error. Could you let me know how to solve the issue? Thanks!

Here is more detail:
I am running SMALR within the virtualenv in a linux system. This is how I ran the test and the error message I got:

[jdu@p-ngs1 ~]$ setup-python2.7.13
[jdu@p-ngs1 ~]$ virtualenv smalr_venv
PYTHONHOME is set.  You *must* activate the virtualenv before using it
New python executable in /home/jdu/smalr_venv/bin/python2.7
Not overwriting existing python script /home/jdu/smalr_venv/bin/python (you must use /home/jdu/smalr_venv/bin/python2.7)
Installing setuptools, pip, wheel...done.
[jdu@p-ngs1 ~]$ . smalr_venv/bin/activate
(smalr_venv) [jdu@p-ngs1 ~]$
(smalr_venv) [jdu@p-ngs1 ~]$
(smalr_venv) [jdu@p-ngs1 ~]$ cd SMALR/test/
(smalr_venv) [jdu@p-ngs1 test]$ ./run_test_SMsn.sh
Preparing to iterate over all contigs in /home/jdu/SMALR/test/nat_shortlib.cmp.h5
        - ref000001 (J99)
15:24:53 [INFO]
15:24:53 [INFO] ====================================
15:24:53 [INFO] Analyzing contig ref000001 (J99)
15:24:53 [INFO] ====================================
15:24:53 [INFO] ref000001 - contig_id:               ref000001
15:24:53 [INFO] ref000001 - contig_name:             J99
15:24:54 [INFO] Partitioning /home/jdu/SMALR/test/wga_shortlib.cmp.h5 into 4 chunks for analysis...
Traceback (most recent call last):
  File "/home/jdu/smalr_venv/bin/call_smalr.py", line 4, in <module>
    __import__('pkg_resources').run_script('smalr==1.0.0', 'call_smalr.py')
  File "/home/jdu/smalr_venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/jdu/smalr_venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/home/jdu/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/EGG-INFO/scripts/call_smalr.py", line 5, in <module>
    sys.exit(main())
  File "/home/jdu/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/smalr_multicontig.py", line 86, in main
    sys.exit( app.run() )
  File "/home/jdu/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/smalr_multicontig.py", line 81, in run
    runner.run()
  File "/home/jdu/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/smalr.py", line 340, in run
    chunk_ipdArrays = self.launch_parallel_molecule_loading( self.Config.wga_cmph5, prefix, wga_movie_name_ID_map, control_ipds )
  File "/home/jdu/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/smalr.py", line 295, in launch_parallel_molecule_loading
    split_mols ))
  File "/home/jdu/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/parse_mol_aligns.py", line 241, in __init__
    self.sites_pos = read_in_motif_sites( self.sites_pos_fn  )
  File "/home/jdu/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/parse_mol_aligns.py", line 138, in read_in_motif_sites
    for line in open(motifSites_fn).xreadlines():
IOError: [Errno 2] No such file or directory: 'gnorin'

**Comment by jbeaulaurier** [comment]
Hello Juan-

Thanks for using SMALR. Hmmm. Is the term 'gnorin' part of a path in your filesystem? I'm not aware of anything in the code base with that name. Let me know. If not, I'll see what else I can find that could be causing this.

Thanks,
John

**Comment by juandu** [comment]
Hi John,

Thanks for your reply. I have searched and could not find ''gnorin" in my
file system. Please let me know if there is any other information I can
provide. Thanks for your help!

Thanks,
Juan

**Comment by jbeaulaurier** [comment]
Hi Juan-

I'm zeroing in on what precisely is going wrong here. There seems to be a problem when the SMALR code attempts to make a call to an R script. Tell me, did you run the SMALR/install.sh script AFTER you created and activated the virtual environment? I want to make sure that you indeed have R installed and available for SMALR to call.

Best,
John

**Comment by juandu** [comment]
Thanks for getting back to me, John!

It was one of our IT staff who installed SMALR on the server, and he is out off office for this and next week. I think he ran the SMALR/install.sh after created and activated the virtual environment (as in the README.md file). Is there a way that I can test now if R is available for SMALR to call?

Thanks,
Juan

**Comment by jbeaulaurier** [comment]
Hi Juan,

From the same SMALR/test directory where you attempted to launch ./run_test_SMsn.sh (and with the virtual environment activated), please try to launch the following command:

`Rscript ../smalr/R/call_motifFinder.r ../smalr/R/motifFinder.r CATG 2 Hpylori_J99.fasta`

Does this write any files in that directory? Or does it produce an error message?

Thanks,
John

**Comment by juandu** [comment]
Hi John,

Yes, it did successfully wrote two files in the folder. Are they correct files? Thank you!

(smalr_venv) [jdu@p-ngs1 test]$ Rscript ../smalr/R/call_motifFinder.r ../smalr/R/motifFinder.r CATG 2 Hpylori_J99.fasta
WARNING: ignoring environment value of R_HOME
Loading required package: seqinr
[1] "Hpylori_J99_CATG_pos.txt"
[1] "Hpylori_J99_CATG_neg.txt"
(smalr_venv) [jdu@p-ngs1 test]$
(smalr_venv) [jdu@p-ngs1 test]$ wc -l Hpylori_J99_CATG_pos.txt
7560 Hpylori_J99_CATG_pos.txt
(smalr_venv) [jdu@p-ngs1 test]$ wc -l Hpylori_J99_CATG_neg.txt
7560 Hpylori_J99_CATG_neg.txt

**Comment by jbeaulaurier** [comment]
Hmmm. Since we can't reach the IT person for a little while, would you be willing to try installing your own version of SMALR locally? I'd be happy to walk you through the installation if you encounter any problems.

First off, it looks like you're activating some resources that have been previously installed globally on your computing system by your IT team (e.g. setup-python2.7.13), so prior to installing SMALR I would make sure that I have all the other SMALR external [dependencies](https://github.com/fanglab/SMALR#dependencies) loaded as well, using whatever command your institution uses to load them:

- bwa >= 0.7
- samtools >= 0.1.18
- R >= 3.0

Once those are loaded and accessible to your system, follow these installation [instructions](https://github.com/fanglab/SMALR#installation). Please don't hesitate to ask me if you have any issues installing locally. Then we'll see whether or not you get the same error message as before. If not, it's probably some environmental issue with how it was installed by your IT person, and we can sort that out with them when they return. But hopefully we can get a local version working for you in the meantime.

Best,
John

**Comment by juandu** [comment]
Thanks John, I will give it a try and get back to you.
Best,
Juan

**Comment by juandu** [comment]
Hi John, I have installed SMALR on my Mac, and it works perfectly. Thanks again for your help!
Juan
